### ISSUE TITLE
[Bug]: Fix security vulnerabilities reported about golang.org/x/text  and github.com/emicklei/go-restful

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#124]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

Github security alerts have been triggered for the following imported Go packages.
https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot/29
https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot/54
https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot/46
https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot/38

### How critical is this bug to you?

Critical - solution is severely limited in value

### What is your operating system?

None

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-848
