### ISSUE TITLE
[Feature]: Add Connector support to Nexus

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#157]
### Tell us the project / group you are associated with

Community (Default)

### What would you like to see implemented?

The nexus connector facility is useful feature that  allows replication of datamodel across cluster boundaries.
The ask is to add connector support to nexus.

### How critical is this feature to you?

Major - important feature to be incorporated as there are no known alternatives in the solution

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-905

**Comment by xmen4xp** [comment]
Connector code is merged to github.
