### ISSUE TITLE
[Bug]: Fix vulnerability flagged by dependabot

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#165]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

Vulnerabilities flagged by dependabot:

https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot

### How critical is this bug to you?

Blocker - solution is unusable

### What is your operating system?

None

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-906
