### ISSUE TITLE
[Feature]: Migrate CLI code base to github

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#172]
### Tell us the project / group you are associated with

Community (Default)

### What would you like to see implemented?

Nexus CLI is a versatile tool for interacting with Nexus.

The ask is to add support for CLI in github.

### How critical is this feature to you?

Blocker - solution is unusable without this feature

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-908
