### ISSUE TITLE
[Feature]: Add graphql-server support to Nexus

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#176]
### Tell us the project / group you are associated with

Community (Default)

### What would you like to see implemented?

Graphql server provides an endpoint to run graphql queries.
The ask is the add support for that server in nexus.

### How critical is this feature to you?

Major - important feature to be incorporated as there are no known alternatives in the solution

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-909
