### ISSUE TITLE
[Feature]: Add nexus datamodel repo

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#184]
### Tell us the project / group you are associated with

Community (Default)

### What would you like to see implemented?

The ask is to introduce a datamodel directory that nexus itself depends on, in the directory "api"

### How critical is this feature to you?

Major - important feature to be incorporated as there are no known alternatives in the solution

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-911
