### ISSUE TITLE
[Feature]: Migrate validation and caliberation code to github

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#199]
### Tell us the project / group you are associated with

Community (Default)

### What would you like to see implemented?

1. The validation repo, which provides validation functionality at runtime should be migrated to github.
2. The caliberation repo, which provides perf toolkit, should be migrated to github.

### How critical is this feature to you?

Major - important feature to be incorporated as there are no known alternatives in the solution

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-915
