### ISSUE TITLE
[Bug]: Documentation for custom api extension is missing

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#209]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

The documentation on how to configure custom rest api is missing.

### How critical is this bug to you?

Major - important to fix

### What is your operating system?

None

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-917
