### ISSUE TITLE
[Bug]: CLI component build fails due to dependency on closed source logging package

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#213]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

CLI component references closed source library: "gitlab.eng.vmware.com/nsx-allspark_users/nexus/golang/pkg/logging"
This results build failure.

### How critical is this bug to you?

Major - important to fix

### What is your operating system?

None

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-918

**Comment by xmen4xp** [comment]
Issue fixed.
