### ISSUE TITLE
Lack of document/tutorial on how to use the compiler

### ISSUE THREAD

**Issue by sushilks** [vmware-tanzu/graph-framework-for-microservices#45]
**Is your feature request related to a problem or limitation? Please describe.**
It's not clear how to use the compiler, a tutorial with an example data model will be great for understanding the scope of the work here. 

**Describe the solution you'd like**
Following will help understand the project if packed with the project 
- An example data model 
- A tutorial on how to build the data model 
- A tutorial on how to deploy the datamodel and APIs on a k8s cluster
- A tutorial on how to write controllers  to interact with the datamodel 
- A multi controller demo application to show case the full application build using the framework. 
**Priority**
Priority with which you would like this feature to be addressed.
- [ ] Blocker - solution is unusable without this feature
- [x] Critical - solution is severely limited in value without this feature
- [ ] Major - important feature to be incorporated as there are no  known alternatives in the solution
- [ ] Minor - nice to have feature that adds value to the solution

**Requester**
Select from the list of well known requesters or select "Community"
- [x] Community

**Comment by mfarinacci-vmware** [comment]
I think there should be a general tutorial in an examples dir

**Comment by xmen4xp** [comment]
Documentation has been added here:
https://github.com/vmware-tanzu/graph-framework-for-microservices/blob/main/docs/getting_started/Playground.md

Detailed DSL documentation is here:
https://github.com/vmware-tanzu/graph-framework-for-microservices/blob/main/compiler/DSL.md
