### ISSUE TITLE
Test bug

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#50]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Version:**
 - Output of the command:    nexus version

**Debug:**

1.  Output of the command:
      - nexus debug
     
3.  For build failures:                  
      - nexus datamodel build --debug

4.  For installation failures:
      - nexus prereq verify
      -  kubectl get pods -A -o yaml

**System:**

**Screenshots**

**Additional context**

**Requester**
Select from the list of well known requesters or select "Community"
- [x] Community
- [ ] Project ServiceMesh
- [ ] Project Mazinger
- [ ] Project Watch

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-634
