### ISSUE TITLE
Github issue template needs to be improved.

### ISSUE THREAD

**Issue by xmen4xp** [vmware-tanzu/graph-framework-for-microservices#51]
**Is your feature request related to a problem or limitation? Please describe.**
Github issue template should be more user friendly.
The current markdown formatting is a little inconvenient to work with.

**Describe the solution you'd like**

**Screenshots**

**Priority**
Priority with which you would like this feature to be addressed.
- [ ] Blocker - solution is unusable without this feature
- [ ] Critical - solution is severely limited in value without this feature
- [ ] Major - important feature to be incorporated as there are no  known alternatives in the solution
- [ ] Minor - nice to have feature that adds value to the solution

**Additional context**

**Describe alternatives you've considered**

**Requester**
Select from the list of well known requesters or select "Community"
- [x] Community
- [ ] Project ServiceMesh
- [ ] Project Mazinger
- [ ] Project Watch

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-635
