### ISSUE TITLE
[Bug]: During installation getting error due to previously failed install.

### ISSUE THREAD

**Issue by sushilks** [vmware-tanzu/graph-framework-for-microservices#73]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

Here is the output of the get-nexus-cli command

graph-framework-for-microservices-test> bash ./get-nexus-cli.sh
Error response from daemon: Conflict. The container name "/nexus-cli" is already in use by container "42dcae36b54f538aeb245e75c22e4572a16c47c924034707b5309fc0e4731eb5". You have to remove (or rename) that container to be able to reuse that name.

### What version are you running?

nexus was not installed yet.

### How critical is this bug to you?

Minor - non-functional bug

### How can we recreate the bug?

run the installation script twice.

### Any debug data that you are able to share?

n/a

### What is your operating system?

MacOS

### Any additional / relevant info

the problem is fixed by running 
docker rm nexus-cli

recommendation: the install script should be able to do this itself.

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-695

**Comment by xmen4xp** [comment]
@ramramu3433  Can you take a look.

**Comment by sankar17** [comment]
@ramramu3433 @xmen4xp   
I created MR for this issue. https://github.com/vmware-tanzu/graph-framework-for-microservices/pull/79
Please review
