### ISSUE TITLE
[Bug]: nexus verify command tries to access gitlab

### ISSUE THREAD

**Issue by sushilks** [vmware-tanzu/graph-framework-for-microservices#75]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

sk@sk-virtual-machine:~/work/graph-test$ nexus version
nexus prereq verifyNexus CLI Upgrade check: failed to fetch remote tags from Nexus CLI repo. Please ensure you are able to clone this repo: `git clone git@gitlab.eng.vmware.com:nsx-allspark_users/nexus-sdk/cli`
NexusCli: v0.0.146
NexusCompiler: v0.0.59
NexusAppTemplates: v0.0.10
NexusDatamodelTemplates: v0.0.22
NexusRuntimeManifets: v0.2.57

### Describe the expected behavior

version check should not access git repo. 

### What version are you running?

posted

### How critical is this bug to you?

Major - important to fix

### How can we recreate the bug?

run the command

### What is your operating system?

Linux

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-697

**Comment by xmen4xp** [comment]
@sankar17 reassigning as you are already working on this.

**Comment by sankar17** [comment]
Issue fixed in below nexus version
❯ nexus version
NexusCli: v0.0.148
NexusCompiler: v0.0.59
NexusAppTemplates: v0.0.10
NexusDatamodelTemplates: v0.0.22
NexusRuntimeManifets: v0.2.57
