### ISSUE TITLE
[Bug]: nexus datamodel build creates files with root permissions

### ISSUE THREAD

**Issue by sushilks** [vmware-tanzu/graph-framework-for-microservices#80]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

After running 
> nexus datamodel build --name orgchart --debug

the build folder was created with the following permissions
> ll build/
total 36
drwxrwxr-x 9 sk   sk   4096 Nov 29 13:38 ./
drwxrwxr-x 3 sk   sk   4096 Nov 29 13:37 ../
drwxr-xr-x 3 root root 4096 Nov 29 13:38 apis/
drwxr-xr-x 5 root root 4096 Nov 29 13:38 client/
drwxr-xr-x 2 root root 4096 Nov 29 13:38 common/
drwxr-xr-x 2 root root 4096 Nov 29 13:38 crds/
drwxr-xr-x 2 root root 4096 Nov 29 13:38 helper/
drwxr-xr-x 2 root root 4096 Nov 29 13:38 nexus-client/
drwxr-xr-x 3 root root 4096 Nov 29 13:40 nexus-gql/

### Describe the expected behavior

All the files in build folder should have the same permissions as the user executing the command. 

### What version are you running?

>nexus version
Nexus CLI Upgrade check: failed to fetch remote tags from Nexus CLI repo. Please ensure you are able to clone this repo: `git clone git@gitlab.eng.vmware.com:nsx-allspark_users/nexus-sdk/cli`
NexusCli: v0.0.146
NexusCompiler: v0.0.59
NexusAppTemplates: v0.0.10
NexusDatamodelTemplates: v0.0.22
NexusRuntimeManifets: v0.2.57

### How critical is this bug to you?

Major - important to fix

### How can we recreate the bug?

just run the command as mentioned

### What is your operating system?

Linux

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-706

**Comment by xmen4xp** [comment]
@sushilks this is fixed now.

For datamodel's that were created before the fix (bootstrapped from previous templates) the following patch needs to be applied

Here is the patch applied for a datamodel called "helloworld"

```

diff --git a/nexus/helloworld/Makefile b/nexus/helloworld/Makefile
index 7a4962c..b3e3d2c 100644
--- a/nexus/helloworld/Makefile
+++ b/nexus/helloworld/Makefile
@@ -33,7 +33,7 @@ datamodel_build:
                        -e CONFIG_FILE=datamodel/nexus.yaml \
                        -e GOPRIVATE=*.eng.vmware.com \
                        -e GOINSECURE=*.eng.vmware.com \
-                       gcr.io/nsx-sm/nexus/compiler:$(TAG); \
+                       gcr.io/nsx-sm/nexus/compiler:$(TAG) /bin/bash -c 'make generate_code && chown -R $(shell id -u):$(shell id -g) .;'; \
        else \
                docker run --pull=missing\
                        --volumes-from=$(CONTAINER_ID) \
`
