### ISSUE TITLE
[Bug]: Missing APIs on the REST explorer

### ISSUE THREAD

**Issue by sushilks** [vmware-tanzu/graph-framework-for-microservices#87]
### Tell us the project / group you are associated with

Community (Default)

### What happened?

In the example there is a call to create manager 
curl -X POST -H 'Content-Type: application/json' -d '{"apiVersion":"root.orgchart.org/v1","kind":"Manager","metadata":{"labels":{"leaders.root.orgchart.org":"MyLeader"},"name":"Manager1"},"spec":{"designation":"Manager","name":"bar"}}'  http://localhost:5000/apis/root.orgchart.org/v1/managers 

--- 
When looking at the explorer (http://localhost:5000/orgchart.org/docs#/) there is no rendered api document and there is no way to create a manager.

---

### Describe the expected behavior

If a API is enabled and its possible to call it from REST server then it should show up in the documentation. If a user wants to create an invisible API they have to explicit mark it in the data-modal as "invisible".

Either we make the REST document match the exposed API or reduce what is exposed to match whats in the document, I would prefer the solution where we publish all callable APIs as rest document.

### What version are you running?

NexusCli: v0.0.146
NexusCompiler: v0.0.59
NexusAppTemplates: v0.0.10
NexusDatamodelTemplates: v0.0.22
NexusRuntimeManifets: v0.2.57

### How critical is this bug to you?

Major - important to fix

### How can we recreate the bug?

follow the playground tutorial.

### What is your operating system?

MacOS

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-713

**Comment by xmen4xp** [comment]
@sushilks 

We provide the way to expose a node via multiple API: kubectl, REST etc.

Kubectl: is admin api. So all nexus nodes are accessible by kubectl (protected by RBAC).

REST: is only available if the nexus node is annotated is expose it as REST API.

In the OrgChart example:

only the Leader node is annotated to require a REST API. The manager node is not asked to be exposed via REST.

```


var LeaderRestAPISpec = nexus.RestAPISpec{
	Uris: []nexus.RestURIs{
		{
			Uri:     "/leader/{root.Leader}",
			Methods: nexus.DefaultHTTPMethodsResponses,
		},
		{
			Uri:     "/leaders",
			Methods: nexus.HTTPListResponse,
		},
	},
}

// nexus-rest-api-gen:LeaderRestAPISpec
type Leader struct {

	// Tags "Root" as a node in datamodel graph
	nexus.Node

	Name          string
	Designation   string
	DirectReports Manager `nexus:"children"`
}

type Manager struct {

	// Tags "Root" as a node in datamodel graph
	nexus.Node

	Name          string
	Designation   string
	DirectReports Engineer `nexus:"children"`
}

```
That is the reason you see REST API missing for it.

This step in the workflow:

```
curl -X POST -H 'Content-Type: application/json' -d '{"apiVersion":"root.orgchart.org/v1","kind":"Manager","metadata":{"labels":{"leaders.root.orgchart.org":"MyLeader"},"name":"Manager1"},"spec":{"designation":"Manager","name":"bar"}}' http://localhost:5000/apis/root.orgchart.org/v1/managers

```

is demonstrating the kubectl - admin api workflow.

**Comment by xmen4xp** [comment]
@sushilks closing this as this is the intentional workflow. Please see the comment above. We can reopen if you disagree.
