### ISSUE TITLE
[Bug]: Remove vulnerabilities dep files reported in gqlgen library

### ISSUE THREAD

**Issue by vishnukavach** [vmware-tanzu/graph-framework-for-microservices#88]
### Contact Details

kvishnu@vmware.com

### Tell us the project / group you are associated with

Community (Default)

### What happened?

Security Alert reported in https://github.com/vmware-tanzu/graph-framework-for-microservices/security/dependabot?q=is%3Aopen+

### How critical is this bug to you?

Critical - solution is severely limited in value

**Comment by ramramu3433** [comment]
New JIRA Created with ID: https://jira.eng.vmware.com/browse/NPT-714

**Comment by vishnukavach** [comment]
Issue Fixed and release
https://github.com/vmware-tanzu/graph-framework-for-microservices/releases/tag/v0.0.60
